114 change profile picture
S-Stanley/ft_transcendence pull request #118
Opened 2022-12-09 22:34 UTC by automaths

Hello la team, 

Cette feature permet le local upload de photo sur la page user pour permettre au user de changer sa pp (la meme page que celle pour changer username et email)

Plusieurs etapes pour se faire
Sur le front: 
- une form (qui s'ouvre et qui se ferme), cette form accept seulement les images (le seul choix lorsqu'on entre dans notre folder pour chercher un fichier)
- Une fois que la form contient le file, ce form est encrypte en 'multipart/form-data', le seul format qu'accepte le module pour enregistrer le fichier (multer). Le fichier est donc charge dans la form, je le lie a une requete POST avec le content type adequat et ca s'envoie sur le back
Sur le back:
- Grace a un module qui s'appelle 'multer', le module officiel de nest pour envoyer des fichiers au back, une guard recupere le fichier automatiquement et l'enregistre dans le dossier indique, soit 'public' a la root de api. 
- Le nom du fichier est un uuid genere aleatoirement (si jamais deux photos de deux users differents avait le meme nom ca aurait ete complique), avec la bonne extension que je parse sur le nom du fichier original
- Donc la on a le fichier enregistre en local dans le dossier public 
- De la, j'utilise un module qui s'appelle serve static module qui est aussi officiel par nest js, qui permet au back de transmettre des fichiers local, donc on dit quelle folder on veut rendre accessible, le folder concerne est celui ou les photos sont enregistre, donc le dossier public
- Donc la on a le backend qui peut donner toutes les photos enregistre grace a un url, en l'occurence "localhost:5000/(le nom du ficher)
- Du coup lorsque le fichier est enregistre, l'url associe au fichier est rendu au front qui enregistre cette url a la place de l'url de l'avatar actuel

Nb: rien a voir avec cette pr, mais j'ai remarque un petit bug lorsqu'on change le username, il retourne sur le profil comme si c'etait un autre utilisateur, je vais regarder ce bug demain mais je pense que c'est parce les pages users sont associe au nickname et pas a l'id 42, affaire a suivre 

C'est plutot une grosse pr, donc n'hesitez pas si vous avez des questions je suis la tout ce weekend 🚀🚀🚀

2022-12-10 14:21 UTC, JulesMaisonneuve approved these changes
Très cool bj

2022-12-10 14:29 UTC, S-Stanley requested changes

2022-12-10 14:29 UTC, S-Stanley commented on webapp/src/helpers/Users.tsx
> +const saveProfilePicture = async (avatar:string, id_42:number): Promise<User | null | undefined> => {
@automaths **question** pourquoi avoir comme retour `User`, `null` et `undefined`. Je pense que le undefined n'est pas necessaire

2022-12-10 14:29 UTC, S-Stanley commented on webapp/src/helpers/Users.tsx
> +        return (req.data.rows[0]);
@automaths je pense qu'il serait plus serait plus interessant de renvoyer req.data.rows[0] directement depuis l'api pour ne pas avoir a le faire sur le front

2022-12-10 14:29 UTC, S-Stanley commented on package.json
> +    "uuid": "^9.0.0"
@automaths Pourquoi il y a des packages ajoutées ici ? Je pense qu'ils devraient etre dans le sous dossier api/ ?

2022-12-10 14:31 UTC, S-Stanley commented
@automaths tu peux ajouter `public/*` dans le `.gitignore` ? Tu peux mettre un README.md dans le dossier public pour qu'il s'envoie via git et qu'il soit deja crée

2022-12-10 14:33 UTC, automaths commented on webapp/src/helpers/Users.tsx
> +const saveProfilePicture = async (avatar:string, id_42:number): Promise<User | null | undefined> => {
okay, c'etait parce que j'avais une erreur de compilation me disant que ca pouvait etre undefined, je regarde

2022-12-10 14:33 UTC, automaths commented on webapp/src/helpers/Users.tsx
> +        return (req.data.rows[0]);
okay

2022-12-10 14:33 UTC, automaths commented on package.json
> +    "uuid": "^9.0.0"
c'est moi j'ai du les installer sur le root sans faire gaffe je les enleve

2022-12-10 15:28 UTC, S-Stanley commented on api/package.json
> +    "u": "^0.1.0"
@automaths **question** c'est quoi le package `u` ? C'est volontaire de l'avoir mis ou c'est une erreur ?

2022-12-10 20:15 UTC, Anysiia approved these changes
Bravo a toi. Tout fonctionne très bien.

2022-12-11 12:54 UTC, S-Stanley approved these changes

2022-12-11 12:54 UTC, merged