Merge pull request #128 from S-Stanley/119-search-bar-for-friend-requ…
S-Stanley/ft_transcendence pull request #133
Opened 2022-12-17 21:18 UTC by S-Stanley

…ests

119 search bar for friend requests

2022-12-17 22:45 UTC, Anysiia approved these changes
Tout fonctionne bien. Par contre les raquettes et la balle du pong sortent de l'écran.

2022-12-17 23:37 UTC, S-Stanley commented
> Tout fonctionne bien. Par contre les raquettes et la balle du pong sortent de l'écran.

Ah oui effectivement, ce n'est pas bon, il faut que je corrige

2022-12-18 12:34 UTC, S-Stanley commented
> Tout fonctionne bien. Par contre les raquettes et la balle du pong sortent de l'écran.

@Anysiia j'ai l'impression qu'on a le meme soucis sur master, tu peux me confirmer ?

2022-12-18 12:57 UTC, automaths reviewed
le refactor est bien mieux, mais toute ma partie multiplayer fonctionnelle repose sur le master, est-ce que c'est possible de la valider apres avoir merge ma partie vu que c'est du refactor, ya de grandes chances que toutes la partie multiplayer pete avec ce refactor

2022-12-18 14:49 UTC, Anysiia commented
> > Tout fonctionne bien. Par contre les raquettes et la balle du pong sortent de l'écran.
> 
> @Anysiia j'ai l'impression qu'on a le meme soucis sur master, tu peux me confirmer ?

Le soucis des raquette est identique sur master, par contre la balle qui sort de l'écran n'est que sur la branche.

2022-12-18 22:45 UTC, S-Stanley commented
> > > Tout fonctionne bien. Par contre les raquettes et la balle du pong sortent de l'écran.
> > 
> > 
> > @Anysiia j'ai l'impression qu'on a le meme soucis sur master, tu peux me confirmer ?
> 
> Le soucis des raquette est identique sur master, par contre la balle qui sort de l'écran n'est que sur la branche.

Peut-etre que c'est du a l'ecran, mais pour moi ça depasse aussi sur develop, mais je vais tout de meme essayer de le résoudre dans cette issue

2022-12-19 00:02 UTC, S-Stanley commented
@Anysiia c'est fix

2022-12-19 06:26 UTC, Anysiia approved these changes

2022-12-19 09:13 UTC, automaths requested changes
Franchement hyper propre ce petit boolean pour voir si on est sur une public page, bien implementer dans la navbar tres tres quali
Tout est bueno sauf sur la page Matchmaking, elle devait surement pas etre la avant le merge, c'est le path /play/matchmaking

2022-12-19 16:13 UTC, JulesMaisonneuve approved these changes

2022-12-19 17:18 UTC, merged