Authentification avec le SSO 42
S-Stanley/ft_transcendence pull request #51
Opened 2022-11-15 23:21 UTC by JulesMaisonneuve

L'authentification est en place: un intercepteur axios a été mis en place pour utiliser automatiquement le token contenu dans le localStorage sur les requêtes axios
Autrement j'ai utilisé TypeOrm sur le backend pour mapper l'entité user et utiliser un repository pour générer automatiquement une requête SQL à la volée, il faudrait appliquer ça sur l'ensemble des entités pour ne plus avoir de SQL écrit dans le code

2022-11-16 00:21 UTC, JulesMaisonneuve commented
Ca ne passe pas les tests car ils étaient basés sur l'ancien système d'authentification, il faudrait les retirer est-ce qu'on est OK là dessus ?

2022-11-16 07:56 UTC, Anysiia reviewed
Effectivement vu qu'on ne va plus se loguer via le système mail / password les tests correspondant à ces checks ne sont plus d'actualité.
Par contre je me demande si ça serait possible de conserver l'autre type d'authentification le temps de faire les tests. Vous en pensez-quoi?
Je rajouterai bien un ficher .env.prod.sample avec les deux variables "CLIENT_ID et "CLIENT_SECRET" avec des valeurs vides.

2022-11-16 07:56 UTC, Anysiia commented on api/src/services/user.service.ts
> +        bodyFormData.append('client_id', 'u-s4t2ud-6694130f6db913ca3cd2ea1112756a01c8af82f732601f915369707b205c3b1c');
Je mettrais plutôt ça: 
` bodyFormData.append('client_id', process.env.CLIENT_ID);`

2022-11-16 07:56 UTC, Anysiia commented on api/src/app.module.ts
> +      }),
Est-ce possible d'utiliser plutôt : 
`port: process.env.POSTGRES_PORT,
username : process.env.POSTGRES_USER,
database: process.env.POSTGRES_DB
`

2022-11-16 07:56 UTC, Anysiia commented on webapp/src/pages/Login/Login.tsx
> +    const code_url = 'https://api.intra.42.fr/oauth/authorize?client_id=u-s4t2ud-6694130f6db913ca3cd2ea1112756a01c8af82f732601f915369707b205c3b1c&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Foauth2-r
Est-ce qu'il existe un moyen d'éviter d'avoir cette longue url en dur dans le code?

2022-11-16 23:48 UTC, JulesMaisonneuve commented on api/src/app.module.ts
> +      }),
Oui, j'ai changé en utilisant les variables d'environnement

2022-11-16 23:53 UTC, JulesMaisonneuve commented on webapp/src/pages/Login/Login.tsx
> +    const code_url = 'https://api.intra.42.fr/oauth/authorize?client_id=u-s4t2ud-6694130f6db913ca3cd2ea1112756a01c8af82f732601f915369707b205c3b1c&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Foauth2-r
> Effectivement vu qu'on ne va plus se loguer via le système mail / password les tests correspondant à ces checks ne sont plus d'actualité. Par contre je me demande si ça serait possible de conserver l'autre type d'authentification le temps de faire les tests. Vous en pensez-quoi? Je rajouterai bien un ficher .env.prod.sample avec les deux variables "CLIENT_ID et "CLIENT_SECRET" avec des valeurs vides.

Plutôt que d'avoir deux systèmes d'authentification, on peut utiliser une extension qui change le header et simuler un autre utilisateur pour faire des tests (ModHeader sur chrome). Comment ça je ne suis pas sûr d'avoir compris ?

2022-11-16 23:53 UTC, JulesMaisonneuve commented
> Effectivement vu qu'on ne va plus se loguer via le système mail / password les tests correspondant à ces checks ne sont plus d'actualité. Par contre je me demande si ça serait possible de conserver l'autre type d'authentification le temps de faire les tests. Vous en pensez-quoi? Je rajouterai bien un ficher .env.prod.sample avec les deux variables "CLIENT_ID et "CLIENT_SECRET" avec des valeurs vides.

2022-11-16 23:54 UTC, JulesMaisonneuve commented
> Effectivement vu qu'on ne va plus se loguer via le système mail / password les tests correspondant à ces checks ne sont plus d'actualité. Par contre je me demande si ça serait possible de conserver l'autre type d'authentification le temps de faire les tests. Vous en pensez-quoi? Je rajouterai bien un ficher .env.prod.sample avec les deux variables "CLIENT_ID et "CLIENT_SECRET" avec des valeurs vides.

Plutôt que d'avoir deux systèmes d'authentification, on peut utiliser une extension qui change le header et simuler un autre utilisateur pour faire des tests (ModHeader sur chrome). Comment ça je ne suis pas sûr d'avoir compris ?

2022-11-16 23:57 UTC, JulesMaisonneuve commented on webapp/src/pages/Login/Login.tsx
> +    const code_url = 'https://api.intra.42.fr/oauth/authorize?client_id=u-s4t2ud-6694130f6db913ca3cd2ea1112756a01c8af82f732601f915369707b205c3b1c&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Foauth2-r
Oui bonne idée, est ce que juste concaténer les infos serait une bonne méthode ou il y a mieux ?

2022-11-17 00:02 UTC, JulesMaisonneuve commented on api/src/services/user.service.ts
> +        bodyFormData.append('client_id', 'u-s4t2ud-6694130f6db913ca3cd2ea1112756a01c8af82f732601f915369707b205c3b1c');
Ce n'était pas un secret donc je l'avais laissé tel quel mais c'est modifié !

2022-11-17 00:59 UTC, S-Stanley requested changes

2022-11-17 00:59 UTC, S-Stanley commented on api/src/app.module.ts
> +        host: 'localhost',
@JulesMaisonneuve **issue:** le build ne fonctionne pas de mon coté. J'ai cette erreur:

```
Error: connect ECONNREFUSED 127.0.0.1:5432
ft_transcendence-api-1       |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1283:16)
```


Je pense que c'est du a cette ligne

```js
host: 'localhost',
```

C'est surement lié a [ce soucis](https://github.com/S-Stanley/ft_transcendence/pull/29#discussion_r1020193153) precedemment resolue.

2022-11-17 00:59 UTC, S-Stanley commented on api/src/app.module.ts
> +        port: +process.env.POSTGRES_PORT,
@JulesMaisonneuve **question:** pourquoi il y a un `+` a la ligne 25 ?

2022-11-17 00:59 UTC, S-Stanley commented on api/src/app.module.ts
> +        synchronize: true
@JulesMaisonneuve **question:** a quoi correspond `synchronize` qu'est-ce que cela permet de faire ?

2022-11-17 00:59 UTC, S-Stanley commented on api/src/dtos/profile.dto.ts
> +}
@JulesMaisonneuve **question:** cela ne me dérange pas, mais pourquoi avoir choisis de mettre les interfaces dans un fichier externe et dans une interface, pourquoi ne pas l'avoir mis  directement dans le retour des fonctions ?

2022-11-17 00:59 UTC, S-Stanley commented on api/src/entities/user.entity.ts
> +}
@JulesMaisonneuve **question** je n'ai pas encore pu tester du au probleme de build remonté plus haut, mais j'ai l'impression que tu utilises un nouveau schema, pourquoi ne pas avoir utilisé les seeds et les functions que l'on avait déjà avec `node-pg` ?

2022-11-17 00:59 UTC, S-Stanley commented on api/src/middleware.ts
> +        const token = req.headers?.authorization;
@JulesMaisonneuve **question** finalement tu comptes utilisé le token fournis par l'api de 42 sur toutes l'app ?

2022-11-17 00:59 UTC, S-Stanley commented on api/src/services/user.service.ts
> +import { Injectable } from "@nestjs/common";
@JulesMaisonneuve **question:** pourquoi avoir crée un tout nouveau services et pas utilisé le controller qu'on avait déjà ?

2022-11-17 00:59 UTC, S-Stanley commented on api/src/services/user.service.ts
> +        const FormData = require('form-data');
@JulesMaisonneuve **nitpick:** peux-tu deplacer ces imports en haut du fichier avec les autres ?

2022-11-17 00:59 UTC, S-Stanley commented on api/src/services/user.service.ts
> +    }
@JulesMaisonneuve **suggestion:** je trouve cette fonction difficilement lisible et donc maintenable, penses-tu pouvoir utiliser async/await plutot ?

2022-11-17 00:59 UTC, S-Stanley commented on database/tables.sql
> -
@JulesMaisonneuve **question:** pourquoi avoir supprimé totalement l'ancienne maniere de faire et ne pas s'adapter plutot ?

2022-11-17 00:59 UTC, S-Stanley commented on webapp/src/components/menu.tsx
> +import { stringify } from 'querystring';
@JulesMaisonneuve **todo:** tu as un import (stringify) qui n'est pas utilisé peut-tu le delete stp ?

2022-11-17 00:59 UTC, S-Stanley commented on webapp/src/components/menu.tsx
> +        localStorage.removeItem('token');
@JulesMaisonneuve **question:** pourquoi ne pas avoir utilisé `localStorage.clear();` ? Pourquoi l'avoir refactor ?

2022-11-17 00:59 UTC, S-Stanley commented on webapp/src/pages/messagerie/Messagerie.tsx
>          if (req) {
@JulesMaisonneuve **question:** j'ai du mal a comprendre ce bout de code, il y a `req` qui est set a `null` puis qui est check dans un if plus loin. Peux-tu m'expliquer stp ?

2022-11-17 08:05 UTC, Anysiia commented
> > Effectivement vu qu'on ne va plus se loguer via le système mail / password les tests correspondant à ces checks ne sont plus d'actualité. Par contre je me demande si ça serait possible de conserver l'autre type d'authentification le temps de faire les tests. Vous en pensez-quoi? Je rajouterai bien un ficher .env.prod.sample avec les deux variables "CLIENT_ID et "CLIENT_SECRET" avec des valeurs vides.
> 
> @Anysiia Plutôt que d'avoir deux systèmes d'authentification, on peut utiliser une extension qui change le header et simuler un autre utilisateur pour faire des tests (ModHeader sur chrome). Comment ça, je ne suis pas sûr d'avoir compris ?

Ok je ne connaissais pas ModHeader. Je vais voir si elle existe aussi sur firefox et comment elle s'utilise.

L'idée derrière un fichier .env.sample ou .env.prod.sample c'est d'avoir dans tes fichiers push un fichier qui t'indique les secrets que tu as à modifier.

2022-11-17 15:18 UTC, JulesMaisonneuve commented on api/src/app.module.ts
> +        port: +process.env.POSTGRES_PORT,
`port:` attend un number or `process.env.POSTGRES_PORT` renvoie une string donc pour convertir en number je met + devant

2022-11-17 15:20 UTC, JulesMaisonneuve commented on api/src/dtos/profile.dto.ts
> +}
Il y avait beaucoup de code et déjà 2 interfaces dans user.service.ts donc pour alléger un peu j'avais créé un autre fichier

2022-11-17 15:21 UTC, JulesMaisonneuve commented on database/tables.sql
> -
On m'a déconseillé d'avoir des fichiers SQL dans le projet donc j'ai essayé de trouver une autre méthode

2022-11-17 15:45 UTC, JulesMaisonneuve commented on api/src/app.module.ts
> +        synchronize: true
De ce que j'ai lu c'est pour créer automatiquement le schéma de la base de données et update la base de données

2022-11-17 15:49 UTC, JulesMaisonneuve commented on webapp/src/components/menu.tsx
> +        localStorage.removeItem('token');
Comme il n'y a pour l'instant que le token dans le localStorage j'avais fait comme ça mais `localStorage.clear();` marche aussi oui

2022-11-17 15:52 UTC, JulesMaisonneuve commented on webapp/src/components/menu.tsx
> +        localStorage.removeItem('token');
Je n'avais pas vu que d'autres choses que le token était contenues dans le localStorage, utiliser clear() est mieux en effet

2022-11-17 22:43 UTC, JulesMaisonneuve commented on api/src/services/user.service.ts
> +import { Injectable } from "@nestjs/common";
Je voulais éviter de mettre de la logique dans le controller

2022-11-17 23:10 UTC, JulesMaisonneuve commented on api/src/middleware.ts
> +        const token = req.headers?.authorization;
C'est-à-dire ? J'ai remplacé token par authorization ici car il faut le header "Authorization: Bearer"

2022-11-17 23:52 UTC, S-Stanley commented on api/src/app.module.ts
> +        host: 'localhost',
@JulesMaisonneuve et que vaut `process.env.POSTGRES_HOST` ? Sur mon .env je n'ai pas cette variable

2022-11-17 23:54 UTC, S-Stanley commented on api/src/app.module.ts
> +        port: +process.env.POSTGRES_PORT,
@JulesMaisonneuve je ne connaissais pas cette possibilité, j'ai toujours utilisé `parseInt()`, merci de m'apprendre un nouveau truc!

Mais du coup, j'ai l'impression que cela fonctionnait quand meme bien avant sans la conversion ?

2022-11-17 23:55 UTC, S-Stanley commented on api/src/app.module.ts
> +        synchronize: true
@JulesMaisonneuve  D'accord!

2022-11-17 23:56 UTC, S-Stanley commented on api/src/middleware.ts
> +        const token = req.headers?.authorization;
@JulesMaisonneuve je veux dire, ici c'est bien pour utilisé le token sur toutes l'application ? (et non pas que pour recuperer les infos de l'api 42) ?

2022-11-17 23:57 UTC, S-Stanley commented on database/tables.sql
> -
@JulesMaisonneuve pourquoi il ne faudrait pas avoir des fichiers SQL dans le projet ?

2022-11-18 00:02 UTC, S-Stanley commented on api/src/app.module.ts
> +        host: 'localhost',
PS: autant pour moi, c'etait une variable du docker-compose que j'avais moi meme mis 😅 ça fonctionne avec !

2022-11-21 21:39 UTC, S-Stanley commented on api/src/dtos/profile.dto.ts
> +}
On a pris la decision de gerer toutes les interfaces dans des fichiers externes

2022-11-21 21:40 UTC, S-Stanley commented on api/src/entities/user.entity.ts
> +}
Vu a l'oral, on va utiliser des fonctions SQL quand il y a beaucoup de checks et l'ORM pour les petites routes

2022-11-21 21:41 UTC, S-Stanley commented on api/src/middleware.ts
> +        const token = req.headers?.authorization;
@JulesMaisonneuve up pour cette question

2022-11-21 21:43 UTC, S-Stanley commented
@JulesMaisonneuve est-ce que tu peux fixup les commits stp ?

2022-11-21 22:06 UTC, JulesMaisonneuve commented on api/src/middleware.ts
> +        const token = req.headers?.authorization;
Oui

2022-11-21 22:45 UTC, S-Stanley commented on api/src/configs/userconnected.decorator.ts
> +
@JulesMaisonneuve **question** a quoi correspond ce decorateur ? Qu'est-ce qu'il permet de faire ?

2022-11-21 23:43 UTC, JulesMaisonneuve commented on api/src/configs/userconnected.decorator.ts
> +
Il permet de récupérer les infos de l'utilisateur (email, nickname) sans devoir injecter le repository à chaque fois

2022-11-22 07:36 UTC, Anysiia commented on api/.env.prod.sample
> +CLIENT_SECRET=
C'est moi qui avait émis l'idée de créer ce fichier

2022-11-23 20:58 UTC, S-Stanley commented on api/.env.prod.sample
> +CLIENT_SECRET=
@Anysiia oui je sais, j'avais proposé une contre idée mais elle n'a pas été choisis

2022-11-23 20:58 UTC, S-Stanley commented on api/src/configs/userconnected.decorator.ts
> +
@JulesMaisonneuve injecter le repository ? C'est a dire ?

2022-11-23 21:22 UTC, Anysiia commented on api/.env.prod.sample
> +CLIENT_SECRET=
Tu aurais préféré qu'on utilise quoi? Des infos sur la config dans le readme, autre chose? Moi ça ne me gène pas, c'est juste une pratique qu'on m'a apprise.

2022-11-23 21:34 UTC, JulesMaisonneuve commented on api/src/configs/userconnected.decorator.ts
> +
Il faut injecter le repository dans le constructeur d'une classe pour pouvoir récupérer des données dans le repository (la table de la base de données)

2022-11-23 21:39 UTC, Anysiia approved these changes

2022-11-23 21:39 UTC, S-Stanley approved these changes

2022-11-23 21:39 UTC, merged