add frontend material ui
S-Stanley/ft_transcendence pull request #72
Opened 2022-11-27 13:15 UTC by automaths

j'ai add mon frontend, j'ai enleve ma data, si vous approuvez je commencerai a complexifier les modeles pour ajouter des stats
Vous pouvez acceder au frontend sur les path new/home new/... (voir routes index.tsx)
L'url de redirection de l'api dans le login.tsx a ete change, n'oubliez pas de mettre la votre :)

2022-11-27 14:01 UTC, S-Stanley commented
@automaths est-ce que tu peux nous ajouter comme reviewer stp ?

2022-11-27 14:30 UTC, S-Stanley requested changes

2022-11-27 14:30 UTC, S-Stanley commented on webapp/src/pages/Login/Login.tsx
> +    const code_url = `https://api.intra.42.fr/oauth/authorize?client_id=u-s4t2ud-8eb36c218c1ff84e8e4a815e0a21d0b2ce13d4712f1e1cce95761c6fbcfaa960&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Foauth2-r
@automaths **todo** est-ce que tu peux remettre ton client_id et ton redirect_uri dans le `.env` stp ?

Et est-ce que tu peux remettre `response_type=code` aussi stp ? Sinon ça ne fonctionne pas

C'est une meilleur pratique au niveau securite, est-ce que tu peux m'expliquer pourquoi tu l'as modifier ?

2022-11-27 14:30 UTC, S-Stanley commented on webapp/src/pages/NewFrontend/Home/Welcome.tsx
> +// import { Copyright } from "@mui/icons-material"
@automaths **suggestion** peux-tu delete cette ligne inutilisé ?

2022-11-27 14:30 UTC, S-Stanley commented on webapp/src/pages/NewFrontend/User/components/AccountProfile.tsx
> +	}, [])
@automaths **nitpick** peux-tu sortir la requete axios a l'exterieur du useEffect dans une autre fonction ? Cela permettra que tu n'auras pas besoin de disable eslint sur la ligne

2022-11-27 14:30 UTC, S-Stanley commented on webapp/src/pages/NewFrontend/Home/components/Choose.tsx
> +    </React.Fragment>
@automaths il y a beaucoup d'endroit où tu utilises des indentations de 2, est-ce que tu peux modifier partout pour mettre soit
* des spaces de 4 (ma preference perso)
* ou des tabulations qui ont pour l'equivalent 4 spaces ?
Ça nous permettra d'etre tous aligne sur la meme indentation.

C'est une tache un peu relou mais il y a une fonctionnalité sur vscode en bas de chaque page qui permet de le faire assez vite

2022-11-27 14:32 UTC, S-Stanley commented
@automaths est-ce que tu peux modifier le message de commit stp ? Car je ne le trouve pas assez descriptif. Que penses-tu de:

```
feat(webapp): add page play, stats, users and leaderboard #69
```

Plus d'info sur le format du commit [dans cet article](https://www.conventionalcommits.org/en/v1.0.0/).

2022-11-27 14:54 UTC, automaths commented on webapp/src/pages/Login/Login.tsx
> +    const code_url = `https://api.intra.42.fr/oauth/authorize?client_id=u-s4t2ud-8eb36c218c1ff84e8e4a815e0a21d0b2ce13d4712f1e1cce95761c6fbcfaa960&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Foauth2-r
c'est vrai c'est juste que j'avais pas encore fait mon .env je le fix

2022-11-27 15:06 UTC, automaths commented on webapp/src/pages/NewFrontend/Home/Welcome.tsx
> +// import { Copyright } from "@mui/icons-material"
c'est fait

2022-11-27 15:06 UTC, automaths commented on webapp/src/pages/NewFrontend/Home/components/Choose.tsx
> +    </React.Fragment>
je vais remettre ca en space de 4 !

2022-11-27 15:08 UTC, automaths commented on webapp/src/pages/NewFrontend/User/components/AccountProfile.tsx
> +	}, [])
je vais la supp, mais ok je note pour la prochaine fois

2022-11-27 15:27 UTC, Anysiia reviewed
Je l'ai déjà dis dans un fichier mais: 
- supprimer les import * de react pour lister les elements reacts que tu importe.
-voir les appels axios dans useEffect() 

Sinon j'approuve ce design. Je saurai vivre sans noir & blanc ;)

2022-11-27 15:27 UTC, Anysiia commented on webapp/src/pages/NewFrontend/Home/components/Title.tsx
> +
Est-ce que tu pourras déplacer cette interface dans le dossier interfaces?

2022-11-27 15:27 UTC, Anysiia commented on webapp/src/pages/NewFrontend/Home/components/Title.tsx
> +import * as React from 'react';
Globalement pour l'ensembles des fichiers, je ne sais pas si c'est une bonne pratique d'importer tout react. J'aurais plutot tendance a importer seulement les éléments dont j'ai besoin

2022-11-27 15:27 UTC, Anysiia commented on webapp/src/pages/NewFrontend/Home/components/listItems.tsx
> +);
Est-ce que ça serait pas mieux de créer puis d'exporter les elements?

2022-11-27 15:27 UTC, Anysiia commented on webapp/src/pages/NewFrontend/Statistics/UserStats.tsx
> +				xs={12}
Ici j'ajouterai une className au grid pour éviter d'avoir autant de code identique. (a vérifier si c'est possible pour la balise grid).
Mais comme ça le fichier css aurait juste cette information une fois, et pour tous les éléments qui ont exactement les memes valeurs, on pourrait leur indiquer une className identique.

2022-11-27 16:45 UTC, S-Stanley commented
@automaths il reste encore des fichiers avec la mauvaise indentation

* webapp/src/pages/NewFrontend/Home/Welcome.tsx
* webapp/src/pages/NewFrontend/Statistics/UserStats.tsx
* webapp/src/pages/NewFrontend/User/Account.tsx
* webapp/src/pages/NewFrontend/Utils/Copyright.tsx

2022-11-27 16:56 UTC, S-Stanley requested changes

2022-11-27 16:56 UTC, S-Stanley commented on webapp/src/pages/NewFrontend/Home/components/Connected.tsx
> +}
@automaths **nitpick** dans l'ideal il faut mettre cette fonction dans le component react (fonction `Connected()`)

2022-11-27 16:56 UTC, S-Stanley commented on webapp/src/pages/NewFrontend/Home/components/match-history.js
> +            }, [])
@automaths **nitpick** est-ce que tu peux mettre aussi cette requete http a l'exterieur du useEffect ?

2022-11-27 16:56 UTC, S-Stanley commented on webapp/src/pages/NewFrontend/Leaderboard/customer/customer-list-toolbar.js
> +                </Button> */}
@automaths **nitpick** est-ce que tu peux delete le code commenté non utilisé ?

2022-11-27 16:56 UTC, S-Stanley commented on webapp/src/pages/NewFrontend/Play/Launch.tsx
> +        // event.preventDefault();
@automaths **nitpick** est-ce que tu peux delete le code commenté non utilisé ? (la fonction et son appel aussi du coup sinon elle sera vide)

2022-11-27 16:56 UTC, S-Stanley commented on webapp/src/pages/NewFrontend/Statistics/components/match-history.js
> +            }, [])
@automaths **nitpick** est-ce que tu peux mettre la requete a l'exterieur du use effect ?

2022-11-27 16:56 UTC, S-Stanley commented on webapp/src/pages/NewFrontend/Statistics/components/match-history.js
> +        {/* <CardHeader title="Match History" /> */}
@automaths **nitpick** peut-tu delete le code commenté non utilisé ?

2022-11-27 16:56 UTC, S-Stanley commented on webapp/src/pages/NewFrontend/User/components/AccountDetails.tsx
> +                                // helperText="Please specify the first name"
@automaths **nitpick** peut-tu delete le code commenté non utilisé ?

2022-11-27 16:56 UTC, S-Stanley commented on webapp/src/pages/NewFrontend/User/components/AccountDetails.tsx
> +                                // helperText="Please specify the first name"
@automaths **nitpick** peut-tu delete le code commenté non utilisé ?

2022-11-27 16:56 UTC, S-Stanley commented on webapp/src/pages/NewFrontend/Utils/Copyright.tsx
> +        <Link color="inherit" href="https://github.com/automaths/ft_transcendence">
@automaths **suggestion** peux-tu remplacer l'url du git vers le project ? (https://github.com/S-Stanley/ft_transcendence)

2022-11-28 00:02 UTC, JulesMaisonneuve commented
Comme on l'a évoqué rapidement à l'oral peut-être à l'avenir garder la navbar en haut avec photo/nickname/bouton disconnect, sinon le design est nickel

2022-11-28 23:40 UTC, automaths commented on webapp/src/pages/NewFrontend/Home/components/Connected.tsx
> +}
je sais pas ce qu'on va en faire pour l'instant, j'ai pas compris ou tu veux que je la mette

2022-11-28 23:41 UTC, automaths commented on webapp/src/pages/NewFrontend/Statistics/UserStats.tsx
> +				xs={12}
oui oui ya quelques optis a faire pour le front apres je suis pas encore expert, je vais essayer de me concentrer sur le chat mais oui a faire carrement !

2022-11-28 23:41 UTC, automaths commented on webapp/src/pages/NewFrontend/Home/components/listItems.tsx
> +);
oui c'est sur qu'il faudra reorganiser je le ferai quand j'ai un moment

2022-11-28 23:41 UTC, automaths commented on webapp/src/pages/NewFrontend/Home/components/Title.tsx
> +import * as React from 'react';
ca a l'air d'etre une meilleure pratique en effet, c'est plus clair

2022-11-28 23:42 UTC, automaths commented on webapp/src/pages/NewFrontend/Home/components/Title.tsx
> +import * as React from 'react';
c'est fait

2022-11-28 23:46 UTC, automaths commented on webapp/src/pages/NewFrontend/Home/components/Title.tsx
> +
elle etait pas necessaire au front, ca compliquait les choses je l'ai supprime

2022-11-28 23:47 UTC, automaths commented on webapp/src/pages/NewFrontend/Home/components/match-history.js
> +            }, [])
bueno

2022-11-28 23:48 UTC, automaths commented on webapp/src/pages/NewFrontend/Leaderboard/customer/customer-list-toolbar.js
> +                </Button> */}
bueno

2022-11-28 23:48 UTC, automaths commented on webapp/src/pages/NewFrontend/Play/Launch.tsx
> +        // event.preventDefault();
bueno

2022-11-28 23:49 UTC, automaths commented on webapp/src/pages/NewFrontend/Statistics/components/match-history.js
> +            }, [])
bueno

2022-11-28 23:49 UTC, automaths commented on webapp/src/pages/NewFrontend/User/components/AccountDetails.tsx
> +                                // helperText="Please specify the first name"
bueno, ca veut dire quoi nitpick ?

2022-11-28 23:50 UTC, automaths commented on webapp/src/pages/NewFrontend/User/components/AccountDetails.tsx
> +                                // helperText="Please specify the first name"
bueno

2022-11-28 23:51 UTC, automaths commented on webapp/src/pages/NewFrontend/Utils/Copyright.tsx
> +        <Link color="inherit" href="https://github.com/automaths/ft_transcendence">
kinder bueno

2022-11-29 00:32 UTC, automaths commented
Les modifs ont ete faites, il y aura surement du refactoring, pour l'instant tout est fonctionnel pour s'attaquer au back, creer de la data, continuer le chat etc ce que je commence a faire demain
J'ai laisse toutes les features de l'ancien front, la messagerie et le chat sont dans le menu de gauche, le username en haut et le logout sur l'icone en haut a gauche

2022-11-29 09:19 UTC, Anysiia reviewed
Tout est globalement fonctionnel. Par contre tu as des conflits et les elements du pong ne sont plus là. J'imagine donc que ta branche n'est pas à jour avec master. 

Tu pourrais ajouter des issues pour les elements que tu penses qu'il sera necessaire de modifier dans le futur. 

Tu as beaucoup de fichiers .js est-ce que c'est normal?

2022-11-29 19:36 UTC, S-Stanley commented on webapp/src/pages/NewFrontend/Home/components/listItems.tsx
> +);
Om pourrais le rajouter dans [eslint](https://eslint.org/docs/latest/rules/), je pense qu'il y a une regle pour ca

2022-11-29 19:38 UTC, S-Stanley commented on webapp/src/pages/NewFrontend/User/components/AccountDetails.tsx
> +                                // helperText="Please specify the first name"
@automaths c'est une "framework" pour les commentaires de review qui permet de rendre ces dernieres moins "tendu" xD 

Plus d'info: https://conventionalcomments.org/

2022-11-29 22:50 UTC, S-Stanley approved these changes

2022-11-29 22:55 UTC, Anysiia approved these changes

2022-11-29 23:00 UTC, JulesMaisonneuve approved these changes

2022-11-29 23:01 UTC, merged