18 sauvegarder lhistorique des matches
S-Stanley/ft_transcendence pull request #83
Opened 2022-12-01 22:44 UTC by automaths

Implementation de l'historique des parties: 
- nouveau modele dans la db (history)
- deux path dans history controller : un POST pour ajouter un historique, un GET pour recuperer tous les historiques
- dans le front l'historique s'affiche sur le home et dans l'onglet statistiques
- dans l'onglet statistiques cumuls des stats de l'historique (nombre de victoires, defaites, de pongs (coups), ratio etc ...

La db est vide au lancement, donc faites au moins une partie pour voir l'historique ! Aussi la partie n'est pas tres passionnante, elle est en un point et good luck pour faire perdre l'ordi ... donc l'historique n'est pas tres passionnant non plus, mais il est bien fonctionnel 

Je vais faire des fixtures soon, ca sera pour une nouvelle pr

2022-12-02 15:07 UTC, JulesMaisonneuve commented on webapp/src/helpers/History.tsx
> +                token: localStorage.getItem('token'),
Je ne suis pas sûr qu'on ait encore besoin de rajouter le token manuellement à chaque fois, on a justement un intercepteur axios qui s'occupe de rajouter le token à chaque requête

2022-12-02 17:05 UTC, Anysiia approved these changes

2022-12-02 17:10 UTC, JulesMaisonneuve approved these changes
Carré !

2022-12-03 15:08 UTC, S-Stanley requested changes

2022-12-03 15:08 UTC, S-Stanley commented on webapp/src/helpers/History.tsx
> +                token: localStorage.getItem('token'),
@automaths **todo** comme le dit @JulesMaisonneuve tu n'as normalement pas besoin de rajouter le headers. Il y a deja la config qui le set automatiquement [ici](https://github.com/S-Stanley/ft_transcendence/blob/master/webapp/src/index.tsx#L26)

2022-12-03 15:08 UTC, S-Stanley commented on webapp/src/pages/Home/components/match-history.js
> +// import { format } from 'date-fns';
@automaths **todo** peut-tu delete le code non utilise stp ?

2022-12-03 15:08 UTC, S-Stanley commented on webapp/src/pages/Home/components/match-history.js
> +        setValues(res.data.result.reverse());
@automaths **suggestion** je pense qu'il est preferable de faire le rebase cote back pour les performances, ce n'est pas tres grave de le laisser là ceci dit.

Si tu veux faire le change je pense que tu peux faire un ORDER BY create_at sur ta requete sql

2022-12-03 15:08 UTC, S-Stanley commented on webapp/src/pages/Home/components/match-history.js
> +                                        {/* {format(Date.parse(value.createdAt), 'dd/MM/yyyy')} */}
@automaths **todo** peux-tu delete le code commente non utilise stp ?

2022-12-03 15:08 UTC, S-Stanley commented on webapp/src/pages/Statistics/components/match-history.js
> +/* ************************************************************************** */
@automaths **question** pourquoi il y a un header de 42 ici ?

2022-12-03 15:08 UTC, S-Stanley commented on webapp/src/pages/Statistics/components/match-history.js
> +// import { format } from 'date-fns';
@automaths **todo** peux-tu delete le code commente non utilise stp ?

2022-12-03 15:08 UTC, S-Stanley commented on webapp/src/pages/Statistics/components/match-history.js
> +                                        {/* {format(Date.parse(value.createdAt), 'dd/MM/yyyy')} */}
@automaths **todo** peux-tu delete le code commente non utilise stp ?

2022-12-03 15:08 UTC, S-Stanley commented
@automaths **todo** le linter de l'api ne passe pas (https://github.com/S-Stanley/ft_transcendence/actions/runs/3603242427/jobs/6071200170)

2022-12-03 16:22 UTC, automaths commented on api/src/entities/history.entity.ts
> +import { Column, Entity, PrimaryGeneratedColumn } from "typeorm";
il me faut le score de l'adversaire ainsi que son nom pour afficher l'historique des parties (1 - 0 contre xx), pour l'instant c'est hardcode vu qu'il n'y a pas de multijoueur

2022-12-03 16:24 UTC, automaths commented on api/src/entities/history.entity.ts
> +    opp_name: string
je suis parti du principe que s'il y avait une seule grande array avec tous les matchs, chacun des joueurs posterait leur resultat a la fin du match, donc deux history par match, cela peut etre change a un avec toutes les infos d'un coup, je compte le changer si besoin lorsque le multijoueur sera implemente

2022-12-03 16:25 UTC, automaths commented on database/tables.sql
> +    created_at          DATE DEFAULT NULL
Ok super je modifie ca

2022-12-03 16:25 UTC, automaths commented on webapp/src/pages/Home/components/match-history.js
> +// import { format } from 'date-fns';
ok

2022-12-03 16:26 UTC, automaths commented on webapp/src/pages/Home/components/match-history.js
> +        setValues(res.data.result.reverse());
ok super bonne idee

2022-12-03 16:27 UTC, automaths commented on webapp/src/pages/Home/components/match-history.js
> +                                        {/* {format(Date.parse(value.createdAt), 'dd/MM/yyyy')} */}
oui

2022-12-03 16:27 UTC, automaths commented on webapp/src/pages/Statistics/components/match-history.js
> +/* ************************************************************************** */
parce que je suis un bon eleve, aucune idee ceci dit mauvaise manip

2022-12-03 16:28 UTC, automaths commented on webapp/src/pages/Statistics/components/match-history.js
> +// import { format } from 'date-fns';
oui j'aurais du check desole

2022-12-03 16:28 UTC, automaths commented on webapp/src/pages/Statistics/components/match-history.js
> +                                        {/* {format(Date.parse(value.createdAt), 'dd/MM/yyyy')} */}
oui

2022-12-03 17:16 UTC, S-Stanley commented on database/tables.sql
> +    created_at          DATE DEFAULT NOW() NOT NULL
@automaths **thought** attention, date comme type ce n'est que le jour, il n'y pas heure/minute/secondes donc ce ne sera pas totalement bien classé sur le profil

2022-12-03 17:44 UTC, S-Stanley approved these changes

2022-12-03 17:58 UTC, merged